---
abstract: 'The great new PoolController!'
author:
  - 'Oleg Tsarkov <olegtsts@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PoolController
provides:
  PoolController:
    file: lib/PoolController.pm
    version: '0.01'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
